#加密配置
jasypt:
  encryptor:
    password: lengleng

server:
  # undertow:
    # io-threads: # 设置IO线程数，最小为2，默认是cpu核数
  tomcat:
    max-threads: 1000 # Maximum amount of worker threads.
    min-spare-threads: 500 # Minimum amount of worker threads

spring:
  redis:
    remote: false        #cachecloud 获取
    host: 10.1.11.204
    port: 6379
    password: 
  rabbitmq:
    host: 10.1.11.204
    port: 5672
    username: pig
    password: lengleng
  http:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

redis:
  cache:
    expiration: 3601

ribbon:
  eager-load:
    enabled: true
    clients: pig-auth,pig-upms-service,pig-instructions-service
  Httpclient:
    enabled: false
  OkHttp:
    enabled: true
  ReadTimeout: 30000
  ConnectTimeout: 30000

feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  client:
    config:
      feignName:
        connectTimeout: 30000
        readTimeout: 30000
  compression:
    request:
      enabled: true
    response:
      enabled: true

hystrix:
  threadpool:
    default:
      coreSize: 1000
      maxQueueSize: 1500
      queueSizeRejectionThreshold: 1600
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: 1000
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
zuul:
  semaphore:
    max-semaphores: 2000
#监控短点配置
management:
  security:
    enabled: false
endpoints:
  actuator:
    enabled: true
  shutdown:
    enabled: false

